name: PRF_Utils_WPF.NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Clean
      run: dotnet clean PRF.Utils.WPF.sln --configuration Release && dotnet nuget locals all --clear
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test --no-build --verbosity normal
      timeout-minutes: 5
    - name: Publish PRF.Utils.WPF to Nuget
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: PRF.Utils.WPF/PRF.Utils.WPF.csproj
        NUGET_KEY: ${{secrets.NUGET_KEY}}
